[build]

command = "node ./create-env.js && npm install && npm run build"
publish = "dist/"

[build.environment]

BUILD_TARGET = "DEFAULT"

[context.demo]

command = "node ./create-env.js && webpack --config webpack/prod.config.js && echo '/* /index.html 200' | cat >dist/_redirects"
# environment = {BUILD_TARGET = "DEMO", NODE_ENV = "production"}
publish = "dist/"

[context.demo.environment]

BUILD_TARGET = "DEMO"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
