[build]

<<<<<<< HEAD
command = "node ./create-env.js && npm install && npm run build"
publish = "dist/"
=======
command = "node ./create-env.js && NODE_ENV=development && npm install && NODE_ENV=production && npm install -g webpack && npm install -g webpack-cli && npm install -g webpack-merge && npm install -g webpack-dev-server && webpack --config webpack/prod.config.js && echo '/* /index.html 200' | cat >dist/_redirects"
>>>>>>> 4254107... install with NODE_ENV != production

[build.environment]

BUILD_TARGET = "DEFAULT"

[context.demo]

command = "node ./create-env.js && NODE_ENV=development && npm install && NODE_ENV=production && npm install -g webpack && npm install -g webpack-cli && npm install -g webpack-merge && npm install -g webpack-dev-server && webpack --config webpack/prod.config.js && echo '/* /index.html 200' | cat >dist/_redirects"
# environment = {BUILD_TARGET = "DEMO", NODE_ENV = "production"}
publish = "dist/"

[context.demo.environment]

BUILD_TARGET = "DEMO"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
